/* Generated By:JavaCC: Do not edit this line. Parser0Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Parser0Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Num = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int MUL = 8;
  /** RegularExpression Id. */
  int DIV = 9;
  /** RegularExpression Id. */
  int EQUALS = 10;
  /** RegularExpression Id. */
  int DEREF = 11;
  /** RegularExpression Id. */
  int TYPE = 12;
  /** RegularExpression Id. */
  int ASS = 13;
  /** RegularExpression Id. */
  int SEQ = 14;
  /** RegularExpression Id. */
  int NEQ = 15;
  /** RegularExpression Id. */
  int BEQ = 16;
  /** RegularExpression Id. */
  int GT = 17;
  /** RegularExpression Id. */
  int GTE = 18;
  /** RegularExpression Id. */
  int LT = 19;
  /** RegularExpression Id. */
  int LTE = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int NOPE = 23;
  /** RegularExpression Id. */
  int LPAR = 24;
  /** RegularExpression Id. */
  int RPAR = 25;
  /** RegularExpression Id. */
  int DEF = 26;
  /** RegularExpression Id. */
  int IN = 27;
  /** RegularExpression Id. */
  int END = 28;
  /** RegularExpression Id. */
  int NEW = 29;
  /** RegularExpression Id. */
  int IF = 30;
  /** RegularExpression Id. */
  int THEN = 31;
  /** RegularExpression Id. */
  int ELSE = 32;
  /** RegularExpression Id. */
  int WHILE = 33;
  /** RegularExpression Id. */
  int DO = 34;
  /** RegularExpression Id. */
  int PRINTLN = 35;
  /** RegularExpression Id. */
  int PRINT = 36;
  /** RegularExpression Id. */
  int REF = 37;
  /** RegularExpression Id. */
  int INT = 38;
  /** RegularExpression Id. */
  int BOOL = 39;
  /** RegularExpression Id. */
  int TRUE = 40;
  /** RegularExpression Id. */
  int FALSE = 41;
  /** RegularExpression Id. */
  int DSEMI = 42;
  /** RegularExpression Id. */
  int Id = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"!\"",
    "\":\"",
    "\":=\"",
    "\";\"",
    "\"~=\"",
    "\"==\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\"def\"",
    "\"in\"",
    "\"end\"",
    "\"new\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"println\"",
    "\"print\"",
    "\"ref\"",
    "\"int\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\";;\"",
    "<Id>",
  };

}
